language: python
before_install:
- pip install pycodestyle
- pip install pytest
- pip install pytest-cov
- pip install coveralls
install:
- pip install -r requirements.txt
- python setup.py install
script:
- find . -name \*.py -exec pycodestyle --max-line-length=120 --ignore=E402 {} +
- pytest --cov=plottwist
after_success:
- coveralls
- cd html && touch .nojekyll && cd ../
deploy:
  - provider: pypi
    skip_cleanup: true
    user: tpoveda
    password:
      secure: E6DvGpsnEf7KSuTXuZW9WeLPhhNBPhp0wJCATMutXS8EcoYu7ThpTPqCk21OOu1PBPFrNIGacjQ++amzVbnLSsjsSsW7QkEg2ukai9zhQnPuwPQGNLSx818klYGAPwqeXW4P9Wj2CjkzQzr2EoWVutPAoWY46iV6D46VVeeM1ptR6NV3DXtLTnOHtZ7a7eHD71gUZyIgwAc/ZLxJb50EL0VkJZXihN4RHPi+BWKOq/DK7jZnL1exMWENPfbyq5cXbI5+pT9mKO/+/Kbg5QHCbfN7ZrFSo6u3SjiSfn0Z6OVXK5dcGyRJO5kMz2gRJOgft3AFzLvPm075Ue6a/+EMktDw5bwIE7S3BUVLwAXbp6jlZrAnBNCd7VmLlIiPlm2l4ENPfXl8RrPPKD+gnRn6eA3+/niqhs9fn07/mXIrGTQqSufP0Kqb2aRix3HrOEKQNgQsLJmYpoY1XqNwg2alyhXiHubJTDXOq9OINvadWMPAX8D38zyb1Don0oIIOZct9VZge1VfhMt7YxyHOGd7cNI+oKRgrr4fy8DUUcaArhOeFmyqMNLhxqXXmJDsTlXpVilxViu7n7aujjbv/vHlDBVsLP1P7eQS638z50nUfDyCpG+ydY5ex9OHup8PcgMgbUt2XvhDW3cDA8SvWJkL3m4kSuQUwtBtiU665upaDgM=
    on:
      branch: master
      tags: true